### ISSUE TITLE
Small correction on technologies 

### ISSUE THREAD

**Issue by EnergyCube** [0xtekgrinder/0xtekgrinder#1]
> Blockchain developer passionate about web3 and open source

You should probably replace `blockchain` with `linked list` and `web3` with `web2++`.
Also, considering how much you love Apple and their Macs, and your use of GAFAM services, maybe you should also reconsider the notion of open source.

This would give us:
> Professional linked list developer passionate about web2++ and GAFAM

**Comment by 0xtekgrinder** [comment]
I can agree that the words used inside my README may not be the bests regarding the state of the industry, however it is the most known terms so I think it is my best interest to keep them. Regarding the second statement, I don't think my vision of open source is truly wrong, there are differents and in my opinion all the technologies that I'm building should be open source.
